on:
  workflow_call:
    inputs:
      env:
        description: 'GitHub Environment (dev, test, prod, etc.)'
        required: true
        type: string
      terraform_dir:
        required: false
        type: string
        default: infra
      destroy:
        required: false
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    environment: ${{ inputs.env }}

    env:
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Verify Azure Context
        run: |
          echo "Logged in as:"
          az account show --output table
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config=env/backend.${{ inputs.env }}.config
        working-directory: ${{ inputs.terraform_dir }}

      - name: Terraform Plan
        run: |
          if [ "${{ inputs.destroy }}" = "true" ]; then
            terraform plan -destroy -var-file=env/${{ inputs.env }}.tfvars -out=tfplan
          else
            terraform plan -var-file=env/${{ inputs.env }}.tfvars -out=tfplan
          fi
        working-directory: ${{ inputs.terraform_dir }}

      - name: Terraform Apply
        working-directory: ${{ inputs.terraform_dir }}
        run: terraform apply tfplan

      - name: Get Static Web App API Key
        if: ${{ inputs.destroy == false }}
        working-directory: infra
        run: |
          echo "SWA_API_KEY=$(terraform output -raw static_web_app_api_key)" >> $GITHUB_ENV

      - name: Download Build Artifacts
        uses: actions/download-artifact@v7
        with:
          name: dist
          path: dist

      - name: Replace config.json
        run: |
          cp "dist/@cashburn/app/browser/config/config.${{ inputs.env }}.json" "dist/@cashburn/app/browser/config/config.json"

      - name: Deploy to Azure Static Web Apps
        if: ${{ inputs.destroy == false }}
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.SWA_API_KEY }}
          action: upload
          app_location: 'dist/@cashburn/app/browser'
          output_location: ''
          skip_app_build: true
